version: '3.8'

networks:
   network:
       external: true
       name: 'network'

services:
  movies-api:
    image: doconnor/movies-api:1.0
    container_name: api
    environment:
      - MONGODB_URI=mongodb://admin:secret@mongo:27017
      - REDIS_URI=redis://redis
      - ENABLE_WRITING_HANDLERS=false
    depends_on:
      - mongo
      - redis
    ports:
      - '9000:9000'
    networks:
      - network

  mongo:
    image: mongo:8.0-rc
    container_name: mongo
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - network
    volumes:
      - ./db:/data/db 

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - network

  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    container_name: express
    restart: always
    ports: 
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks: 
      - network